version: '3'
services:
  app:
    build: .
    container_name: bug-tracker-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bugtracker
      - JWT_SECRET=super_secret
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bugtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
